Move all deps to workspace toml
paritytech/subxt pull request #932
Opened 2023-04-25 16:02 UTC by jsdw

Move all of our dependencies (and version) to the workspace toml, and reference them in crates where used.

Why?
- Prevents dupe versions of crates from being used across the workspace (or, makes it very much "opt-in" and explicit if you do need this)
- Makes bumping Subxt versions easy for releasing; just one file to change
- Makes bumping Substrate dep versions easier; all in one place.
- Makes it clear how many crates we import in total; might motivate us to cut down a bit ;)

**Note:** `package = "parity-scale-codec"` is needed in each crate, because the macro uses https://github.com/bkchr/proc-macro-crate, which relies on finding that key in the local TOML (see https://github.com/bkchr/proc-macro-crate/issues/34). The alternative is giving a manual crate path in all uses of the macro, but doesn't seem worth it.

2023-04-25 16:05 UTC, tadeohepperle approved these changes

2023-04-26 08:01 UTC, niklasad1 commented on testing/wasm-tests/target/CACHEDIR.TAG
remove?!

2023-04-26 08:02 UTC, niklasad1 commented on Cargo.toml
> +substrate-runner = { path = "testing/substrate-runner" }
```suggestion
substrate-runner = { path = "testing/substrate-runner" }

```

2023-04-26 08:05 UTC, niklasad1 commented on Cargo.toml
> +    ## This cannot be a workspace dependency, because it requires
can you move this comment above `exclude = ["testing/wasm-tests"]` instead? 

I found it a little bit hard to understand

2023-04-26 08:06 UTC, niklasad1 requested changes
Great, just remove some unintended committed files and it should be ready to go

2023-04-26 09:11 UTC, jsdw commented on testing/wasm-tests/target/debug/.cargo-lock
Argh these must have turned up when I ran `cargo hack` locally!

2023-04-26 09:11 UTC, jsdw commented
Comment moved and added files gone :)

2023-04-26 09:13 UTC, niklasad1 commented on testing/wasm-tests/Cargo.lock
do want this?

2023-04-26 09:14 UTC, niklasad1 approved these changes

2023-04-26 09:29 UTC, jsdw commented on testing/wasm-tests/Cargo.lock
I debated that; I assume it's used to determine the deps to download for tests so maybe good to keep it to ensure complete consistency between us :)

2023-04-26 09:32 UTC, merged